Repository GSG-CF05/FashionApp-team3, pull requests merged in 2022-02, with the labels that each got.

#4 1 create file structure
  cart/cart.css
  cart/cart.html
  index.html
  more/more.css
  more/more.html
  product-details/product-details.css
  product-details/product-details.html
  style.css
Labels: approve

#5 Create images. Relates to issue#3
  assets/cart-page/cart1.png
  assets/cart-page/cart2.png
  assets/general-assets/burger-menu.png
  assets/home-page/homepage1.png
  assets/home-page/homepage2.png
  assets/home-page/homepage3.png
  assets/home-page/homepage4.png
  assets/home-page/homepage5.png
  assets/more-page/more1.png
  assets/more-page/more2.png
  assets/more-page/more3.png
  assets/more-page/more4.png
  assets/more-page/more5.png
  assets/more-page/more6.png
  assets/product-detail/productdetail1.png
  assets/quick-note.txt
Labels: approve

#9 6 creating home page
  index.html
  style.css
Labels: approved

#10 create more file in html with header and body contains product and cr…
  more/more.css
  more/more.html
Labels: awaiting-review

#11 First I created two files, an html file and a css file. A 3section a…
  product-details/product-details.css
  product-details/product-details.html
Labels: approved

#13 Created the cart page and styled it according to the figma file. Solves issue #12.
  assets/general-assets/Plus.svg
  assets/general-assets/close.svg
  assets/general-assets/minus.svg
  assets/general-assets/shopping-bag.svg
  cart/cart.css
  cart/cart.html
Labels: approved

#14 write readMe file and describe why we made this app and write the tea…
  README.md
Labels: approved
